"""LLM-Economist style macro/policy event generation.

Events are generated by an LLM, then passed through the EventResolutionPipeline
which validates constraints, resolves plausibility via a GM-style referee,
and computes deterministic chain reactions.
"""

from __future__ import annotations

import json
import random
from typing import Dict

from financial_town.config import SimulationConfig
from financial_town.engines.event_resolution import EventResolutionPipeline
from financial_town.llm import AgentLLMClient
from financial_town.simulation.state import TownState

SPEND_CATEGORIES = [
  "groceries",
  "utilities",
  "transport",
  "healthcare",
  "education",
  "retail",
  "entertainment",
]


class LLMEconomistEngine:
  def __init__(self, config: SimulationConfig, rng: random.Random):
    self.config = config
    self.rng = rng
    self.client = AgentLLMClient(
      provider=config.llm_economist_provider,
      model=config.llm_economist_model,
      temperature=config.llm_economist_temperature,
      max_output_tokens=config.llm_economist_max_output_tokens,
      timeout_sec=config.llm_timeout_sec,
    )
    self.resolution_pipeline = EventResolutionPipeline(config, rng)

  def _clamp(self, value: float, lower: float, upper: float) -> float:
    return max(lower, min(upper, value))

  def _safe_float(self, value, default: float = 0.0) -> float:
    try:
      return float(value)
    except Exception:
      return default

  def _should_run(self, step: int) -> bool:
    interval = max(1, int(self.config.llm_economist_every_steps))
    return step % interval == 0

  def _system_prompt(self) -> str:
    return (
      "You are an LLM-Economist style macro policy generator in an agent-based economy simulation. "
      "Given current macro/policy/household stress signals, generate one plausible macro event for this step. "
      "Return JSON only with keys: note, macro_delta, policy_delta, price_shock. "
      "macro_delta may contain gdp_growth, inflation, unemployment_rate, housing_growth deltas. "
      "policy_delta may contain layoff_rate, stimulus_payment, housing_subsidy, central_bank_rate deltas. "
      "price_shock may contain global_price_pct and category_price_pct. "
      "category_price_pct is a map over: groceries, utilities, transport, healthcare, education, retail, entertainment. "
      "Keep deltas small and realistic for one period: macro/policy around [-0.05, 0.05], price pct around [-0.12, 0.15]."
    )

  def _user_prompt(self, state: TownState) -> str:
    unemployment = state.macro.unemployment_rate
    inflation = state.macro.inflation
    debt = sum(l.remaining_principal for l in state.loans.values())
    employed = len([p for p in state.people.values() if p.employment_status.value == "employed"])

    payload = {
      "step": state.step,
      "scenario": state.scenario_name,
      "macro": {
        "gdp_growth": state.macro.gdp_growth,
        "inflation": inflation,
        "unemployment_rate": unemployment,
        "housing_growth": state.macro.housing_growth,
      },
      "policy": {
        "layoff_rate": state.policy.layoff_rate,
        "stimulus_payment": state.policy.stimulus_payment,
        "housing_subsidy": state.policy.housing_subsidy,
        "central_bank_rate": state.policy.central_bank_rate,
      },
      "signals": {
        "population": len(state.people),
        "employed_count": employed,
        "loan_count": len(state.loans),
        "total_debt": round(debt, 2),
      },
      "prices": {
        "consumer_price_index": round(float(getattr(state, "consumer_price_index", 1.0) or 1.0), 6),
        "category_price_multipliers": {
          k: round(float(v), 6)
          for k, v in (getattr(state, "category_price_multipliers", {}) or {}).items()
        },
      },
    }
    return "Input JSON:\n" + json.dumps(payload, indent=2)

  def _track_call(self, state: TownState, prompt_tokens: int, completion_tokens: int, ok: bool) -> None:
    if "calls_step" not in state.llm_stats:
      state.llm_stats["calls_step"] = 0.0
      state.llm_stats["calls_total"] = 0.0
      state.llm_stats["errors_step"] = 0.0
      state.llm_stats["errors_total"] = 0.0
      state.llm_stats["prompt_tokens_step"] = 0.0
      state.llm_stats["completion_tokens_step"] = 0.0
      state.llm_stats["prompt_tokens_total"] = 0.0
      state.llm_stats["completion_tokens_total"] = 0.0

    state.llm_stats["calls_step"] += 1.0
    state.llm_stats["calls_total"] += 1.0
    state.llm_stats["prompt_tokens_step"] += float(prompt_tokens)
    state.llm_stats["completion_tokens_step"] += float(completion_tokens)
    state.llm_stats["prompt_tokens_total"] += float(prompt_tokens)
    state.llm_stats["completion_tokens_total"] += float(completion_tokens)
    if not ok:
      state.llm_stats["errors_step"] += 1.0
      state.llm_stats["errors_total"] += 1.0

  def run_step(self, state: TownState) -> None:
    if not self.config.enable_llm_economist:
      return
    if not self._should_run(state.step):
      return

    if not self.client.available:
      raise RuntimeError(self.client.unavailable_reason)

    result = self.client.generate_json(self._system_prompt(), self._user_prompt(state))
    self._track_call(
      state,
      prompt_tokens=int(result.get("prompt_tokens", 0)),
      completion_tokens=int(result.get("completion_tokens", 0)),
      ok=bool(result.get("ok", False)),
    )
    if not result.get("ok"):
      if self.config.llm_strict_mode:
        raise RuntimeError(result.get("error", "llm_economist_generation_failed"))
      return

    raw_payload: Dict[str, object] = result.get("payload", {})

    resolved = self.resolution_pipeline.process_event(state, raw_payload)

    chain_summaries = [
      {"type": c.get("type"), "effect": c.get("effect"),
       "delta": c.get("applied_delta", c.get("delta")),
       "reasoning": c.get("reasoning", "")}
      for c in resolved.chain_reactions
    ]

    event = {
      "step": state.step,
      "note": resolved.note,
      "rejected": resolved.rejected,
      "resolution_reasoning": resolved.resolution_reasoning,
      "macro_delta": resolved.macro_delta,
      "policy_delta": resolved.policy_delta,
      "price_shock": resolved.price_shock,
      "chain_reactions": chain_summaries,
      "validation_violations": resolved.validation.violations,
      "pipeline_stats": self.resolution_pipeline.stats,
      "post_state": {
        "macro": {
          "gdp_growth": round(state.macro.gdp_growth, 5),
          "inflation": round(state.macro.inflation, 5),
          "unemployment_rate": round(state.macro.unemployment_rate, 5),
          "housing_growth": round(state.macro.housing_growth, 5),
        },
        "policy": {
          "central_bank_rate": round(state.policy.central_bank_rate, 5),
          "layoff_rate": round(state.policy.layoff_rate, 5),
        },
        "consumer_price_index": round(
          float(getattr(state, "consumer_price_index", 1.0)), 5
        ),
      },
    }

    if not resolved.rejected:
      state.macro_events.append(event)

    state.llm_events.append({
      "step": state.step,
      "type": "llm_economist_event",
      **event,
    })
